# Generated by Django 4.2.6 on 2023-10-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampImages',
            fields=[
                ('main_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('main_image_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'camp_images',
                'managed': False,
            },
        ),
    ]
