# Generated by Django 4.2.6 on 2023-10-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camping_app', '0002_campimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampUtility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_no', models.IntegerField(blank=True, null=True)),
                ('electric', models.IntegerField(blank=True, null=True)),
                ('wifi', models.IntegerField(blank=True, null=True)),
                ('firewood', models.IntegerField(blank=True, null=True)),
                ('warm_water', models.IntegerField(blank=True, null=True)),
                ('walking_load', models.IntegerField(blank=True, null=True)),
                ('sports_ground', models.IntegerField(blank=True, null=True)),
                ('market', models.IntegerField(blank=True, null=True)),
                ('water_playground', models.IntegerField(blank=True, null=True)),
                ('athletic_fac', models.IntegerField(blank=True, null=True)),
                ('adv_ground', models.IntegerField(blank=True, null=True)),
                ('trampoline', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'camp_utility',
                'managed': False,
            },
        ),
    ]
